name: Call Local API

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  call-api:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Start Local API (C#)
        run: |
          nohup dotnet run --urls "http://localhost:5057" &

      - name: Wait for API to be ready
        run: sleep 5

      - name: Send POST request with PR payload
        run: |
          echo '${{ toJson(github.event.pull_request) }}' > pr_payload.json
          curl -X POST http://localhost:5057/api/pr \
            -H "Content-Type: application/json" \
            -d @pr_payload.json
