name: Call Local API

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  call-api:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Start Local API (C#)
        run: |
          # Start your C# local API (replace with your actual start command)
          nohup dotnet run --urls "http://localhost:5057" &

      - name: Wait for API to be ready
        run: sleep 5

      - name: Call Local API
        run: |
          curl http://localhost:5057/api/pr
