name: Call Local API on PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  call-api:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Update based on your project

      - name: Restore dependencies
        run: dotnet restore ./PRProject/PRProject.csproj

      - name: Build API
        run: dotnet build --configuration Release ./PRProject/PRProject.csproj

      - name: Start Local API
        run: |
          nohup dotnet run --project ./PRProject/PRProject.csproj --urls "http://localhost:5057" &

      - name: Wait for API to be ready
        run: sleep 5

      - name: Send POST request with PR payload
        run: |
          echo '${{ toJson(github.event.pull_request) }}' > pr_payload.json
          curl -X POST http://localhost:5057/api/pr \
            -H "Content-Type: application/json" \
            -d @pr_payload.json
