name: Trigger AI Agent on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  trigger-ai-agent:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted 
    steps:
      - name: Send payload to Custom API
        run: |
          echo '${{ toJson(github.event.pull_request) }}' > pr_payload.json
          curl -X POST http://localhost:5057/api/pr \
            -H "Content-Type: application/json" \
            -d @pr_payload.json
